# Generated by Django 5.0 on 2023-12-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antarasite', '0003_contactusinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDCInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
