# Generated by Django 5.0 on 2024-01-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antarasite', '0005_servicedpinquiry_servicehhinquiry_servicekwinquiry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusinquiry',
            options={'verbose_name': 'About Us - Inquiry', 'verbose_name_plural': 'About Us - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='contactusinquiry',
            options={'verbose_name': 'Contact Us - Inquiry', 'verbose_name_plural': 'Contact Us - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Home Page - Inquiry', 'verbose_name_plural': 'Home Page - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='servicedcinquiry',
            options={'verbose_name': 'Service Diabetes Consultation - Inquiry', 'verbose_name_plural': 'Service Diabetes Consultation - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='servicedpinquiry',
            options={'verbose_name': 'Service DC Inquiry', 'verbose_name_plural': 'Service DC Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='servicehhinquiry',
            options={'verbose_name': "Service Men's Health - Inquiry", 'verbose_name_plural': "Service Men's Health - Inquiries"},
        ),
        migrations.AlterModelOptions(
            name='servicekwinquiry',
            options={'verbose_name': 'Service Weight Management - Inquiry', 'verbose_name_plural': 'Service Weight Management - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='servicencinquiry',
            options={'verbose_name': 'Service Naturopathic Consultations - Inquiry', 'verbose_name_plural': 'Service Naturopathic Consultations - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='servicendcinquiry',
            options={'verbose_name': 'Service Nutrition and Diet - Inquiry', 'verbose_name_plural': 'Service Nutrition and Diet - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='servicescinquiry',
            options={'verbose_name': 'Service Senior Care - Inquiry', 'verbose_name_plural': 'Service Senior Care - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='servicewwinquiry',
            options={'verbose_name': 'Service Women Wellness - Inquiry', 'verbose_name_plural': 'Service Women Wellness - Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='serviceytinquiry',
            options={'verbose_name': 'Service Yoga Sessions - Inquiry', 'verbose_name_plural': 'Service Yoga Sessions - Inquiries'},
        ),
    ]
